# Generated by Django 2.0.9 on 2018-12-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181202_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='langitude',
            new_name='longitude',
        ),
    ]
