# Generated by Django 2.0.9 on 2018-12-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181203_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='name',
            field=models.CharField(default='My Circle', max_length=255),
        ),
    ]
